/** Sprite order is stable: four objects per row, four rows per atlas. */
export const FURNITURE_SETS = [
  {id:"library",label:"Library",items:["Oak Bookcase","Mint Bookcase","Reading Armchair","Book Trolley"],prices:[75,55,60,35]},
  {id:"gamer",label:"Gamer",items:["Dual Monitor Desk","RGB Gaming Chair","Glass PC Tower","Retro Arcade"],prices:[100,65,80,90]},
  {id:"plants",label:"Greenhouse",items:["Monstera","Fern Stand","Indoor Palm","Daisy Basket"],prices:[25,40,45,20]},
  {id:"plush",label:"Plush Friends",items:["Teddy Bear","Bunny Plush","Cat Plush","Frog Plush"],prices:[30,30,30,30]},
  {id:"kitchen",label:"Kitchen",items:["Mint Refrigerator","Cream Oven","Oak Sink Counter","Breakfast Island"],prices:[85,75,65,90]},
  {id:"patio",label:"Garden Living",items:["Patio Dining Set","Flower Swing","Garden Hammock","Barbecue Grill"],prices:[80,70,55,65]},
  {id:"spa",label:"Spa Retreat",items:["Bubbling Jacuzzi","Sauna Lounger","Parasol Daybed","Spa Towel Rack"],prices:[140,55,85,30]},
  {id:"curtains",label:"Curtains",items:["Pink Bow Curtains","Lavender Star Curtains","Sage Linen Curtains","Gothic Velvet Curtains"],prices:[35,35,35,40]},
  {id:"lounge",label:"Living Room",items:["Sage Corner Sofa","Oak TV Console","Nesting Coffee Tables","Cream Stone Fireplace"],prices:[100,85,45,95]},
  {id:"bedroom",label:"Bedroom",items:["Lavender Double Bed","Bedside Lamp Cabinet","Oval Mirror Vanity","Floral Privacy Screen"],prices:[110,40,75,50]},
  {id:"bathroom",label:"Bathroom",items:["Clawfoot Bathtub","Glass Shower","Sage Sink Vanity","Laundry Station"],prices:[100,90,65,80]},
  {id:"accents",label:"Little Treasures",items:["Candle Tray","Wildflower Vase","Family Photo Display","Amethyst Cluster"],prices:[20,25,20,35]},
  {id:"kitchenware",label:"Kitchen Extras",items:["Corner Kitchen Counter","Wall Kitchen Cabinet","Coffee Station","Retro Toaster"],prices:[70,45,55,25]},
  {id:"reading",label:"Reading Nook",items:["Ladder Library","Corner Bookcase","Brass Reading Lamp","Magazine Rack"],prices:[100,65,35,25]},
  {id:"gaming",label:"Gaming Studio",items:["Triple Monitor Desk","Console Station","Racing Simulator","Headphone Stand"],prices:[120,85,140,25]},
  {id:"music",label:"Music Room",items:["Upright Piano","Guitar Stand","Drum Kit","Record Cabinet"],prices:[120,50,95,65]},
  {id:"cuddles",label:"More Plush Friends",items:["Capybara Plush","Duck Plush","Dragon Plush","Penguin Plush"],prices:[35,30,40,30]},
  {id:"botanical",label:"Botanical Garden",items:["Bonsai Tree","Succulent Collection","Hanging Ivy","Mini Greenhouse"],prices:[45,25,30,85]},
  {id:"petcorner",label:"Pet Corner",items:["Canopy Pet Bed","Feeding Station","Scratching Tower","Play Tunnel"],prices:[55,35,65,45]},
  {id:"outdoors",label:"Outdoor Retreat",items:["Flower Gazebo","Picnic Table","Fire Pit","Lily Pond"],prices:[120,70,65,100]},
  {id:"poolside",label:"Poolside",items:["Garden Pool","Cedar Sauna","Outdoor Shower","Pool Float Basket"],prices:[160,140,65,30]},
  {id:"wallart",label:"Wall Gallery",items:["Botanical Painting","Round Gold Mirror","Floating Wall Shelf","Brass Wall Sconce"],prices:[30,45,35,30]},
  {id:"textiles",label:"Soft Furnishings",items:["Round Floral Rug","Cloud Rug","Floor Cushion Trio","Woven Blanket Basket"],prices:[35,35,30,25]},
  {id:"fantasy",label:"Enchanted Home",items:["Potion Table","Magic Bookcase","Mushroom Lamp","Treasure Chest"],prices:[85,100,40,65]},
  {id:"cafe",label:"Corner Cafe",items:["Coffee Bar","Pastry Display","Bistro Table","Chalkboard Menu"],prices:[95,80,55,25]},
  {id:"atelier",label:"Creative Studio",items:["Painting Easel","Sewing Desk","Pottery Wheel","Tool Workbench"],prices:[45,75,85,80]},
] as const;
export type FurnitureSetId = typeof FURNITURE_SETS[number]["id"];
export const SET_FURNITURE = FURNITURE_SETS.flatMap((set,row)=>set.items.map((label,col)=>({
  id:`furniture_set_${set.id}_${col}`,label,price:set.prices[col],collection:set.id,
  scale:set.id==="accents"?.55:set.id==="cuddles"?.65:(set.id==="gaming"&&col===3)||(set.id==="kitchenware"&&col===3)?.5:1,
  floorMat:set.id==="textiles"&&col<2,
  outdoor:["patio","spa","outdoors","poolside"].includes(set.id),
  wallMounted:["curtains","wallart"].includes(set.id) || (set.id==="kitchenware" && col===1) || (set.id==="botanical" && col===2),sprite:56+row*4+col,
})));
